# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: api
output: schemas.gen.go
generate:
  models: true
  embedded-spec: false
