@default:
	@just -u -l

lint:
	npm run lint

format:
	npm run format

install:
	npm install @mui/material @emotion/react @emotion/styled @mui/icons-material

build:
  npm run build

start:
  npm run start

test *args="--coverage":
  CI=true npm run test {{ args }}
