@default:
    @just -u -l

lint:
    npm run lint

format:
    npm run format

build:
    npm run build

dev:
    npm run dev

test *args="src/":
    CI=true npm run test {{ args }}

test-e2e *args:
    CI=true npm run test:e2e {{ args }}

generate:
    npm run generate

npm *args:
    npm {{ args }}

build-push-local:
    # This builds the amd image local and the arm image on the orangepi5-max-ubuntu
    docker buildx build --builder multiarch-builder --platform linux/arm64,linux/amd64 -t 192.168.8.1:5000/local/football-pool/frontend:dev . --output type=registry,registry.insecure=true
