@default:
    @just -u -l

lint:
    npm run lint

format:
    npm run format

build:
    npm run build

dev:
    npm run dev

test *args="src/":
    CI=true npm run test {{ args }}

test-e2e *args:
    CI=true npm run test:e2e {{ args }}

npm *args:
    npm {{ args }}
