# Football Pool PostgreSQL Configuration Example
# Copy this file to config/prod.toml and customize for your PostgreSQL setup

[server]
host = "localhost"
port = "8080"

[database]
type = "postgres"

[database.config]
host = "localhost"
port = 5432
user = "postgres"
password = "password"
dbname = "football_pool"
sslmode = "disable"

[logging]
level = "info"

[espn]
base_url = "https://site.api.espn.com/apis/site/v2/sports/football/nfl"
cache_dir = "assets/cache"
sync_enabled = true
sync_interval = "1h"
cache_expiry = "1000h"

[e2e]
test = false

[theoddsapi]
base_url = "https://api.the-odds-api.com/v4"
region = "us"
api_key = ""