# Football Pool Backend Configuration

[server]
host = "0.0.0.0"
port = "8080"

[database]
type = "sqlite"

[database.config]
file = "football-pool.db"

[logging]
level = "info"

[espn]
base_url = "https://site.api.espn.com/apis/site/v2/sports/football/nfl"
cache_dir = "assets/cache"
sync_enabled = true
sync_interval = "1h"
cache_expiry = "1000h"

[e2e]
test = false

[theoddsapi]
base_url = "https://api.the-odds-api.com/v4"
region = "us"
api_key = ""
