services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "13000:80"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_BACKEND_URL=http://localhost:18080
    depends_on:
      - backend
