version: "2"
formatters:
  enable:
    - gofmt
linters:
  enable:
    - dogsled
    #- dupl
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    #- gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - unparam
    - unused
    - sloglint
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
  settings:
    staticcheck:
      checks: ["all", "-QF1008"]
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (io.ReadCloser).Close
        - (*encoding/json.Decoder).Decode
        - (*encoding/json.Encoder).Encode
        - github.com/spf13/viper.BindEnv
        - (*os.File).Close
        - os.Remove
