@default:
    @just -u -l

build:
    go build -o football-pool ./cmd/main.go

tidy:
    go mod tidy

run:
    go run ./cmd/main.go

run-bin:
    ./football-pool

lint:
    golangci-lint run ./...

format:
    go fmt ./...

test *args="-cover -coverprofile=coverage.txt ./...":
    go test {{ args }}
