@default:
	@just -u -l

build:
	go build -o football-pool ./cmd/main.go

tidy:
  go mod tidy

run:
	go run ./cmd/main.go

seed *args:
  go run ./cmd/seed/main.go {{ args }}

lint:
	golangci-lint run ./...

format:
	go fmt ./...
