/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
  ErrorResponse,
  LoginResponse,
  PlayerResponse,
  RegisterResponse,
  UserListResponse,
  UserResponse,
} from "../../model";

export const getLoginUserResponseMock = (
  overrideResponse: Partial<LoginResponse> = {},
): LoginResponse => ({
  token: faker.string.alpha({ length: { min: 10, max: 20 } }),
  user: {
    id: faker.number.int({ min: undefined, max: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role: faker.string.alpha({ length: { min: 10, max: 20 } }),
    player: faker.helpers.arrayElement([
      {
        id: faker.number.int({ min: undefined, max: undefined }),
        user_id: faker.number.int({ min: undefined, max: undefined }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      undefined,
    ]),
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  },
  ...overrideResponse,
});

export const getLoginUserResponseMock200 = (
  overrideResponse: Partial<LoginResponse> = {},
): LoginResponse => ({
  token: faker.string.alpha({ length: { min: 10, max: 20 } }),
  user: {
    id: faker.number.int({ min: undefined, max: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role: faker.string.alpha({ length: { min: 10, max: 20 } }),
    player: faker.helpers.arrayElement([
      {
        id: faker.number.int({ min: undefined, max: undefined }),
        user_id: faker.number.int({ min: undefined, max: undefined }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      undefined,
    ]),
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  },
  ...overrideResponse,
});

export const getLoginUserResponseMock400 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getLoginUserResponseMock401 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getLoginUserResponseMock500 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getLogoutUserResponseMock400 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getRegisterUserResponseMock = (
  overrideResponse: Partial<RegisterResponse> = {},
): RegisterResponse => ({
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getRegisterUserResponseMock201 = (
  overrideResponse: Partial<RegisterResponse> = {},
): RegisterResponse => ({
  message: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getRegisterUserResponseMock400 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getRegisterUserResponseMock500 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetProfileResponseMock = (
  overrideResponse: Partial<PlayerResponse> = {},
): PlayerResponse => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  user_id: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  address: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetProfileResponseMock200 = (
  overrideResponse: Partial<PlayerResponse> = {},
): PlayerResponse => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  user_id: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  address: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetProfileResponseMock401 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetProfileResponseMock404 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getUpdateProfileResponseMock = (
  overrideResponse: Partial<PlayerResponse> = {},
): PlayerResponse => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  user_id: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  address: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getUpdateProfileResponseMock200 = (
  overrideResponse: Partial<PlayerResponse> = {},
): PlayerResponse => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  user_id: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  address: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getUpdateProfileResponseMock401 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getAdminGetUserResponseMock = (
  overrideResponse: Partial<UserResponse> = {},
): UserResponse => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.string.alpha({ length: { min: 10, max: 20 } }),
  role: faker.string.alpha({ length: { min: 10, max: 20 } }),
  player: faker.helpers.arrayElement([
    {
      id: faker.number.int({ min: undefined, max: undefined }),
      user_id: faker.number.int({ min: undefined, max: undefined }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      address: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    undefined,
  ]),
  created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getAdminGetUserResponseMock200 = (
  overrideResponse: Partial<UserResponse> = {},
): UserResponse => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.string.alpha({ length: { min: 10, max: 20 } }),
  role: faker.string.alpha({ length: { min: 10, max: 20 } }),
  player: faker.helpers.arrayElement([
    {
      id: faker.number.int({ min: undefined, max: undefined }),
      user_id: faker.number.int({ min: undefined, max: undefined }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      address: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    undefined,
  ]),
  created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getAdminGetUserResponseMock401 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getAdminUpdateUserResponseMock = (
  overrideResponse: Partial<UserResponse> = {},
): UserResponse => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.string.alpha({ length: { min: 10, max: 20 } }),
  role: faker.string.alpha({ length: { min: 10, max: 20 } }),
  player: faker.helpers.arrayElement([
    {
      id: faker.number.int({ min: undefined, max: undefined }),
      user_id: faker.number.int({ min: undefined, max: undefined }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      address: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    undefined,
  ]),
  created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getAdminUpdateUserResponseMock200 = (
  overrideResponse: Partial<UserResponse> = {},
): UserResponse => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  email: faker.string.alpha({ length: { min: 10, max: 20 } }),
  role: faker.string.alpha({ length: { min: 10, max: 20 } }),
  player: faker.helpers.arrayElement([
    {
      id: faker.number.int({ min: undefined, max: undefined }),
      user_id: faker.number.int({ min: undefined, max: undefined }),
      name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      address: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    undefined,
  ]),
  created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getAdminUpdateUserResponseMock401 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDeleteUserByEmailResponseMock400 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDeleteUserByEmailResponseMock401 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDeleteUserByEmailResponseMock404 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getAdminListUsersResponseMock = (
  overrideResponse: Partial<UserListResponse> = {},
): UserListResponse => ({
  users: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role: faker.string.alpha({ length: { min: 10, max: 20 } }),
    player: faker.helpers.arrayElement([
      {
        id: faker.number.int({ min: undefined, max: undefined }),
        user_id: faker.number.int({ min: undefined, max: undefined }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      undefined,
    ]),
    pick_count: faker.number.int({ min: undefined, max: undefined }),
    total_wins: faker.number.int({ min: undefined, max: undefined }),
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  pagination: {
    page: faker.number.int({ min: undefined, max: undefined }),
    limit: faker.number.int({ min: undefined, max: undefined }),
    total: faker.number.int({ min: undefined, max: undefined }),
    pages: faker.number.int({ min: undefined, max: undefined }),
  },
  ...overrideResponse,
});

export const getAdminListUsersResponseMock200 = (
  overrideResponse: Partial<UserListResponse> = {},
): UserListResponse => ({
  users: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role: faker.string.alpha({ length: { min: 10, max: 20 } }),
    player: faker.helpers.arrayElement([
      {
        id: faker.number.int({ min: undefined, max: undefined }),
        user_id: faker.number.int({ min: undefined, max: undefined }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      undefined,
    ]),
    pick_count: faker.number.int({ min: undefined, max: undefined }),
    total_wins: faker.number.int({ min: undefined, max: undefined }),
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  pagination: {
    page: faker.number.int({ min: undefined, max: undefined }),
    limit: faker.number.int({ min: undefined, max: undefined }),
    total: faker.number.int({ min: undefined, max: undefined }),
    pages: faker.number.int({ min: undefined, max: undefined }),
  },
  ...overrideResponse,
});

export const getAdminListUsersResponseMock401 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getCreateUsersResponseMock = (): UserResponse[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role: faker.string.alpha({ length: { min: 10, max: 20 } }),
    player: faker.helpers.arrayElement([
      {
        id: faker.number.int({ min: undefined, max: undefined }),
        user_id: faker.number.int({ min: undefined, max: undefined }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      undefined,
    ]),
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  }));

export const getCreateUsersResponseMock201 = (): UserResponse[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    role: faker.string.alpha({ length: { min: 10, max: 20 } }),
    player: faker.helpers.arrayElement([
      {
        id: faker.number.int({ min: undefined, max: undefined }),
        user_id: faker.number.int({ min: undefined, max: undefined }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
        address: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      undefined,
    ]),
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  }));

export const getCreateUsersResponseMock400 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getCreateUsersResponseMock401 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getCreateUsersResponseMock500 = (
  overrideResponse: Partial<ErrorResponse> = {},
): ErrorResponse => ({
  error: faker.string.alpha({ length: { min: 10, max: 20 } }),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getLoginUserMockHandler = (
  overrideResponse?:
    | LoginResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<LoginResponse> | LoginResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/login",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getLoginUserResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getLoginUserMockHandler200 = (
  overrideResponse?:
    | LoginResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<LoginResponse> | LoginResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/login",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getLoginUserResponseMock200(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getLoginUserMockHandler400 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/login",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getLoginUserResponseMock400(),
        ),
        { status: 400, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getLoginUserMockHandler401 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/login",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getLoginUserResponseMock401(),
        ),
        { status: 401, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getLoginUserMockHandler500 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/login",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getLoginUserResponseMock500(),
        ),
        { status: 500, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getLogoutUserMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/logout",
    async (info) => {
      await delay(100);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getLogoutUserMockHandler200 = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/logout",
    async (info) => {
      await delay(100);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getLogoutUserMockHandler400 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/logout",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getLogoutUserResponseMock400(),
        ),
        { status: 400, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getRegisterUserMockHandler = (
  overrideResponse?:
    | RegisterResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<RegisterResponse> | RegisterResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/register",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getRegisterUserResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getRegisterUserMockHandler201 = (
  overrideResponse?:
    | RegisterResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<RegisterResponse> | RegisterResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/register",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getRegisterUserResponseMock201(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getRegisterUserMockHandler400 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/register",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getRegisterUserResponseMock400(),
        ),
        { status: 400, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getRegisterUserMockHandler500 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/register",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getRegisterUserResponseMock500(),
        ),
        { status: 500, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetProfileMockHandler = (
  overrideResponse?:
    | PlayerResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PlayerResponse> | PlayerResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/users/me",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetProfileResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetProfileMockHandler200 = (
  overrideResponse?:
    | PlayerResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PlayerResponse> | PlayerResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/users/me",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetProfileResponseMock200(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetProfileMockHandler401 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/users/me",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetProfileResponseMock401(),
        ),
        { status: 401, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getGetProfileMockHandler404 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/users/me",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getGetProfileResponseMock404(),
        ),
        { status: 404, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getUpdateProfileMockHandler = (
  overrideResponse?:
    | PlayerResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<PlayerResponse> | PlayerResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/users/me/update",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateProfileResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getUpdateProfileMockHandler200 = (
  overrideResponse?:
    | PlayerResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<PlayerResponse> | PlayerResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/users/me/update",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateProfileResponseMock200(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getUpdateProfileMockHandler401 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/users/me/update",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateProfileResponseMock401(),
        ),
        { status: 401, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminGetUserMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/admin/users/:id",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminGetUserResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminGetUserMockHandler200 = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/admin/users/:id",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminGetUserResponseMock200(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminGetUserMockHandler401 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/admin/users/:id",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminGetUserResponseMock401(),
        ),
        { status: 401, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminUpdateUserMockHandler = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/admin/users/:id",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminUpdateUserResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminUpdateUserMockHandler200 = (
  overrideResponse?:
    | UserResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<UserResponse> | UserResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/admin/users/:id",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminUpdateUserResponseMock200(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminUpdateUserMockHandler401 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    "*/api/admin/users/:id",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminUpdateUserResponseMock401(),
        ),
        { status: 401, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getDeleteUserByEmailMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/api/admin/users/delete",
    async (info) => {
      await delay(100);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getDeleteUserByEmailMockHandler204 = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/api/admin/users/delete",
    async (info) => {
      await delay(100);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getDeleteUserByEmailMockHandler400 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/api/admin/users/delete",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteUserByEmailResponseMock400(),
        ),
        { status: 400, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getDeleteUserByEmailMockHandler401 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/api/admin/users/delete",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteUserByEmailResponseMock401(),
        ),
        { status: 401, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getDeleteUserByEmailMockHandler404 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/api/admin/users/delete",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteUserByEmailResponseMock404(),
        ),
        { status: 404, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminListUsersMockHandler = (
  overrideResponse?:
    | UserListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserListResponse> | UserListResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/admin/users",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminListUsersResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminListUsersMockHandler200 = (
  overrideResponse?:
    | UserListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserListResponse> | UserListResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/admin/users",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminListUsersResponseMock200(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getAdminListUsersMockHandler401 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/admin/users",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getAdminListUsersResponseMock401(),
        ),
        { status: 401, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getCreateUsersMockHandler = (
  overrideResponse?:
    | UserResponse[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<UserResponse[]> | UserResponse[]),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/users/create",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateUsersResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getCreateUsersMockHandler201 = (
  overrideResponse?:
    | UserResponse[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<UserResponse[]> | UserResponse[]),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/users/create",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateUsersResponseMock201(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getCreateUsersMockHandler400 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/users/create",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateUsersResponseMock400(),
        ),
        { status: 400, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getCreateUsersMockHandler401 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/users/create",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateUsersResponseMock401(),
        ),
        { status: 401, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};

export const getCreateUsersMockHandler500 = (
  overrideResponse?:
    | ErrorResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ErrorResponse> | ErrorResponse),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/admin/users/create",
    async (info) => {
      await delay(100);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getCreateUsersResponseMock500(),
        ),
        { status: 500, headers: { "Content-Type": "application/json" } },
      );
    },
    options,
  );
};
export const getUserMock = () => [
  getLoginUserMockHandler(),
  getLogoutUserMockHandler(),
  getRegisterUserMockHandler(),
  getGetProfileMockHandler(),
  getUpdateProfileMockHandler(),
  getAdminGetUserMockHandler(),
  getAdminUpdateUserMockHandler(),
  getDeleteUserByEmailMockHandler(),
  getAdminListUsersMockHandler(),
  getCreateUsersMockHandler(),
];
