/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */
import type { TeamDesignation } from "./teamDesignation";

export interface GameRequest {
  week: number;
  season: number;
  home_team: string;
  away_team: string;
  favorite?: TeamDesignation;
  underdog?: TeamDesignation;
  spread: number;
  start_time: string;
}
