/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from "./userResponse";

export interface LoginResponse {
  token: string;
  user: UserResponse;
}
