/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */

export interface PaginationResponse {
  page: number;
  limit: number;
  total: number;
  pages: number;
}
