/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */
import type { PickResponse } from "./pickResponse";
import type { PaginationResponse } from "./paginationResponse";

export interface PickListResponse {
  picks: PickResponse[];
  pagination: PaginationResponse;
}
