/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */

export interface PlayerResponse {
  id: number;
  user_id: number;
  name: string;
  address: string;
}
