/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from "./userResponse";

export interface SurvivorPickResponse {
  id: number;
  user_id: number;
  user?: UserResponse;
  week: number;
  team: string;
  created_at: string;
  updated_at: string;
}
