/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */
import type { UserWithStats } from "./userWithStats";
import type { PaginationResponse } from "./paginationResponse";

export interface UserListResponse {
  users: UserWithStats[];
  pagination: PaginationResponse;
}
