/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Football Pool API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";

import type { GameListResponse, GameResponse } from "../../model";

export const getGetGamesResponseMock = (
  overrideResponse: Partial<GameListResponse> = {},
): GameListResponse => ({
  games: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    week: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    season: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    favorite_team: faker.string.alpha({ length: { min: 10, max: 20 } }),
    underdog_team: faker.string.alpha({ length: { min: 10, max: 20 } }),
    spread: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    start_time: `${faker.date.past().toISOString().split(".")[0]}Z`,
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  pagination: {
    page: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    limit: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    total: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    pages: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
  },
  ...overrideResponse,
});

export const getCreateGameResponseMock = (): GameResponse[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    week: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    season: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    favorite_team: faker.string.alpha({ length: { min: 10, max: 20 } }),
    underdog_team: faker.string.alpha({ length: { min: 10, max: 20 } }),
    spread: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    start_time: `${faker.date.past().toISOString().split(".")[0]}Z`,
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  }));

export const getAdminListGamesResponseMock = (
  overrideResponse: Partial<GameListResponse> = {},
): GameListResponse => ({
  games: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    week: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    season: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    favorite_team: faker.string.alpha({ length: { min: 10, max: 20 } }),
    underdog_team: faker.string.alpha({ length: { min: 10, max: 20 } }),
    spread: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    start_time: `${faker.date.past().toISOString().split(".")[0]}Z`,
    created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
    updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  pagination: {
    page: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    limit: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    total: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
    pages: faker.number.int({
      min: undefined,
      max: undefined,
      multipleOf: undefined,
    }),
  },
  ...overrideResponse,
});

export const getUpdateGameResponseMock = (
  overrideResponse: Partial<GameResponse> = {},
): GameResponse => ({
  id: faker.number.int({
    min: undefined,
    max: undefined,
    multipleOf: undefined,
  }),
  week: faker.number.int({
    min: undefined,
    max: undefined,
    multipleOf: undefined,
  }),
  season: faker.number.int({
    min: undefined,
    max: undefined,
    multipleOf: undefined,
  }),
  favorite_team: faker.string.alpha({ length: { min: 10, max: 20 } }),
  underdog_team: faker.string.alpha({ length: { min: 10, max: 20 } }),
  spread: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  start_time: `${faker.date.past().toISOString().split(".")[0]}Z`,
  created_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  updated_at: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getGetGamesMockHandler = (
  overrideResponse?:
    | GameListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GameListResponse> | GameListResponse),
) => {
  return http.get("*/api/games", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetGamesResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getCreateGameMockHandler = (
  overrideResponse?:
    | GameResponse[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<GameResponse[]> | GameResponse[]),
) => {
  return http.post("*/api/games/create", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateGameResponseMock(),
      ),
      { status: 201, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getAdminListGamesMockHandler = (
  overrideResponse?:
    | GameListResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GameListResponse> | GameListResponse),
) => {
  return http.get("*/api/admin/games", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getAdminListGamesResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getUpdateGameMockHandler = (
  overrideResponse?:
    | GameResponse
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<GameResponse> | GameResponse),
) => {
  return http.put("*/api/admin/games/:id", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getUpdateGameResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDeleteGameMockHandler = (
  overrideResponse?:
    | null
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<null> | null),
) => {
  return http.delete("*/api/admin/games/:id", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};
export const getGamesMock = () => [
  getGetGamesMockHandler(),
  getCreateGameMockHandler(),
  getAdminListGamesMockHandler(),
  getUpdateGameMockHandler(),
  getDeleteGameMockHandler(),
];
