apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "football-pool.fullname" . }}-backend
  labels:
    {{- include "football-pool.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "football-pool.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "football-pool.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            {{- if .Values.postgresql.enabled }}
            - name: FOOTBALL_POOL_DB_TYPE
              value: "postgres"
            - name: FOOTBALL_POOL_DB_HOST
              value: "{{ .Values.postgresql.clusterName }}-rw"
            - name: FOOTBALL_POOL_DB_PORT
              value: "5432"
            - name: FOOTBALL_POOL_DB_NAME
              value: {{ .Values.postgresql.database | quote }}
            - name: FOOTBALL_POOL_DB_USER
              value: {{ .Values.postgresql.username | quote }}
            - name: FOOTBALL_POOL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.clusterName }}-app
                  key: password
            - name: FOOTBALL_POOL_DB_SSLMODE
              value: "disable"
            {{- else }}
            {{- range $key, $val := .Values.backend.config.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            - name: CORS_ALLOWED_ORIGINS
              value: {{ join "," .Values.backend.cors.allowedOrigins | quote }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          {{- if or .Values.backend.usersTomlSecret.enabled (and (not .Values.postgresql.enabled) .Values.backend.sqlite.persistence.enabled) }}
          volumeMounts:
            {{- if .Values.backend.usersTomlSecret.enabled }}
            - name: users-toml
              mountPath: "/app/config/users.toml"
              subPath: "users.toml"
              readOnly: true
            {{- end }}
            {{- if and (not .Values.postgresql.enabled) .Values.backend.sqlite.persistence.enabled }}
            - name: sqlite-data
              mountPath: "/app/data"
            {{- end }}
          {{- end }}
      volumes:
        {{- if .Values.backend.usersTomlSecret.enabled }}
        - name: users-toml
          secret:
            secretName: {{ .Values.backend.usersTomlSecret.secretName }}
        {{- end }}
        {{- if and (not .Values.postgresql.enabled) .Values.backend.sqlite.persistence.enabled }}
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: {{ include "football-pool.fullname" . }}-sqlite
        {{- end }}
