{{- if .Values.postgresql.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgresql.clusterName }}
  labels:
    {{- include "football-pool.labels" . | nindent 4 }}
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: {{ .Values.postgresql.storage.size }}
  bootstrap:
    initdb:
      database: {{ .Values.postgresql.database }}
      owner: {{ .Values.postgresql.username }}
{{- end -}}
