replicaCount: 1

backend:
  image:
    repository: ghcr.io/dhpollack/football-pool/backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
  config:
    # Environment variables for the backend
    # Example:
    # FOOTBALL_POOL_DB_TYPE: "postgres"
    # FOOTBALL_POOL_PG_HOST: "my-postgres"
    # FOOTBALL_POOL_PG_PORT: "5432"
    env: {}
  cors:
    # CORS allowed origins for the backend API
    allowedOrigins:
      - "http://localhost:13000"
      - "https://localhost:13001"
      - "http://localhost:5173"
      - "https://football-pool.local"

  usersTomlSecret:
    enabled: false
    secretName: "" # Name of the secret containing the users.toml file

  sqlite:
    persistence:
      enabled: true
      size: "128Mi"
      # storageClass: "" # Optional: specify a storage class

frontend:
  image:
    repository: ghcr.io/dhpollack/football-pool/frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: football-pool.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: football-pool-tls
  #    hosts:
  #      - football-pool.local

# CloudNativePG cluster deployment
# Prerequisite: The CloudNativePG operator must be installed in the cluster.
postgresql:
  enabled: false
  clusterName: "football-pool-pg"
  database: "football_pool"
  username: "football_pool_user"
  storage:
    size: "1Gi"

# Extra Kubernetes manifests to be applied alongside the main deployment
# Useful for adding Traefik middlewares, additional resources, etc.
extraManifests: []
