name: release-please

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          token: ${{ secrets.GH_PAT_RELEASE_PLEASE }}

      - name: Enable Auto-Merge on Release PR
        if: ${{ steps.release-please.outputs.prs_created }}
        run: |
          PR_NUMBER=$(echo '${{ steps.release-please.outputs.pr }}' | jq -r '.number')
          gh pr merge $PR_NUMBER --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_RELEASE_PLEASE }}
