name: Release Please Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release-please')
    steps:
      - uses: actions/checkout@v4

      - name: Run dummy test
        run: |
          echo "Running tests for release-please branch: ${{ github.head_ref }}"
          echo "This is a dummy test that always passes to enable auto-merge"
          echo "In a real scenario, you would run actual tests here"

