name: release-please

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}

